#
# build stage
#

FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS build

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN New-Item C:/temp -ItemType Directory; \
  New-Item C:/data -ItemType Directory;
WORKDIR C:/temp

ENV PYTHON_VERSION 3.7.9
ENV PYTHON_RELEASE 3.7.9

RUN $url = ('https://www.python.org/ftp/python/{0}/python-{1}-amd64.exe' -f $env:PYTHON_RELEASE, $env:PYTHON_VERSION); \
        Write-Host ('Downloading {0} ...' -f $url); \
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
        Invoke-WebRequest -Uri $url -OutFile 'python.exe'; \
        \
        Write-Host 'Installing ...'; \
# https://docs.python.org/3.7/using/windows.html#installing-without-ui
        Start-Process python.exe -Wait \
                -ArgumentList @( \
                        '/quiet', \
                        'InstallAllUsers=1', \
                        'TargetDir=C:\Python37', \
                        'PrependPath=1', \
                        'Shortcuts=0', \
                        'Include_doc=0', \
                        'Include_pip=0', \
                        'Include_test=0' \
                ); \
        \
#the installer updated PATH, so we should refresh our local value
        $env:PATH = [Environment]::GetEnvironmentVariable('PATH', [EnvironmentVariableTarget]::Machine); \
        \
        Write-Host 'Verifying install ...'; \
        Write-Host '  python --version'; python --version; \
        \
        Write-Host 'Removing ...'; \
        Remove-Item python.exe -Force; \
        \
        Write-Host 'Complete.'

# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/d59197a3c169cef378a22428a3fa99d33e080a5d/get-pip.py
ENV PYTHON_GET_PIP_SHA256 421ac1d44c0cf9730a088e337867d974b91bdce4ea2636099275071878cc189e

RUN Write-Host ('Downloading get-pip.py ({0}) ...' -f $env:PYTHON_GET_PIP_URL); \
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
        Invoke-WebRequest -Uri $env:PYTHON_GET_PIP_URL -OutFile 'get-pip.py'; \
        Write-Host ('Verifying sha256 ({0}) ...' -f $env:PYTHON_GET_PIP_SHA256); \
        if ((Get-FileHash 'get-pip.py' -Algorithm sha256).Hash -ne $env:PYTHON_GET_PIP_SHA256) { \
                Write-Host 'FAILED!'; \
                exit 1; \
        }; \
        \
        Write-Host ('Installing pip ...'); \
        python get-pip.py \
                --disable-pip-version-check \
                --no-cache-dir \
        ; \
        Remove-Item get-pip.py -Force; \
        \
        Write-Host 'Verifying pip install ...'; \
        pip --version; \
        \
        Write-Host 'Complete.'

# Install Requirements for GEOLib

COPY requirements.txt C:\\
RUN pip install -r  C:/requirements.txt

# Install GEOLib

RUN pip install d-geolib

#
# Deploy
#

FROM mcr.microsoft.com/windows/nanoserver:ltsc2019
USER Administrator
COPY --from=build C:\\Python37 C:\\Python37
SHELL ["cmd.exe", "/s", "/c"]
RUN setx /m PATH %PATH%;c:\Python37
USER ContainerUser

