import pytest
from teamcity import is_running_under_teamcity
from tests.utils import TestUtils
from geolib.models import DSettlementModel
from pathlib import Path


class TestRegressionSuite:
    @pytest.mark.systemtest
    @pytest.mark.skipif(
        not is_running_under_teamcity(), reason="Regression tests take a long time."
    )
    @pytest.mark.parametrize(
        "filename",
        [
            pytest.param("bm1-1", id="Input file"),
            pytest.param("bm1-10", id="Input file"),
            pytest.param("bm1-10", id="Input file"),
            pytest.param("bm1-2", id="Input file"),
            pytest.param("bm1-3", id="Input file"),
            pytest.param("bm1-4", id="Input file"),
            pytest.param("bm1-5", id="Input file"),
            pytest.param("bm1-6", id="Input file"),
            pytest.param("bm1-7a", id="Input file"),
            pytest.param("bm1-7b", id="Input file"),
            pytest.param("bm1-8a", id="Input file"),
            pytest.param("bm1-8b", id="Input file"),
            pytest.param("bm1-9a", id="Input file"),
            pytest.param("bm1-9b", id="Input file"),
            pytest.param("bm2-1a", id="Input file"),
            pytest.param("bm2-1b", id="Input file"),
            pytest.param("bm2-2a", id="Input file"),
            pytest.param("bm2-2b", id="Input file"),
            pytest.param("bm2-3", id="Input file"),
            pytest.param("bm2-4", id="Input file"),
            pytest.param("bm2-5a", id="Input file"),
            pytest.param("bm2-5b", id="Input file"),
            pytest.param("bm3-10a", id="Input file"),
            pytest.param("bm3-10b", id="Input file"),
            pytest.param("bm3-10c", id="Input file"),
            pytest.param("bm3-10d", id="Input file"),
            pytest.param("bm3-10e", id="Input file"),
            pytest.param("bm3-10f", id="Input file"),
            pytest.param("bm3-10g", id="Input file"),
            pytest.param("bm3-10h", id="Input file"),
            pytest.param("bm3-10i", id="Input file"),
            pytest.param("bm3-11a", id="Input file"),
            pytest.param("bm3-11b", id="Input file"),
            pytest.param("bm3-11c", id="Input file"),
            pytest.param("bm3-11d", id="Input file"),
            pytest.param("bm3-11e", id="Input file"),
            pytest.param("bm3-11f", id="Input file"),
            pytest.param("bm3-11g", id="Input file"),
            pytest.param("bm3-11h", id="Input file"),
            pytest.param("bm3-11i", id="Input file"),
            pytest.param("bm3-11j", id="Input file"),
            pytest.param("bm3-11k", id="Input file"),
            pytest.param("bm3-11l", id="Input file"),
            pytest.param("bm3-12a", id="Input file"),
            pytest.param("bm3-12b", id="Input file"),
            pytest.param("bm3-13a", id="Input file"),
            pytest.param("bm3-13b", id="Input file"),
            pytest.param("bm3-14a", id="Input file"),
            pytest.param("bm3-14b", id="Input file"),
            pytest.param("bm3-15a", id="Input file"),
            pytest.param("bm3-15b", id="Input file"),
            pytest.param("bm3-15c", id="Input file"),
            pytest.param("bm3-15d", id="Input file"),
            pytest.param("bm3-15e", id="Input file"),
            pytest.param("bm3-15f", id="Input file"),
            pytest.param("bm3-1a", id="Input file"),
            pytest.param("bm3-1b", id="Input file"),
            pytest.param("bm3-1c", id="Input file"),
            pytest.param("bm3-1d", id="Input file"),
            pytest.param("bm3-1e", id="Input file"),
            pytest.param("bm3-1f", id="Input file"),
            pytest.param("bm3-1g", id="Input file"),
            pytest.param("bm3-1h", id="Input file"),
            pytest.param("bm3-2a", id="Input file"),
            pytest.param("bm3-2b", id="Input file"),
            pytest.param("bm3-2c", id="Input file"),
            pytest.param("bm3-2d", id="Input file"),
            pytest.param("bm3-2e", id="Input file"),
            pytest.param("bm3-2f", id="Input file"),
            pytest.param("bm3-2g", id="Input file"),
            pytest.param("bm3-2h", id="Input file"),
            pytest.param("bm3-3a", id="Input file"),
            pytest.param("bm3-3b", id="Input file"),
            pytest.param("bm3-3c", id="Input file"),
            pytest.param("bm3-3d", id="Input file"),
            pytest.param("bm3-3e", id="Input file"),
            pytest.param("bm3-3f", id="Input file"),
            pytest.param("bm3-3g", id="Input file"),
            pytest.param("bm3-3h", id="Input file"),
            pytest.param("bm3-4a", id="Input file"),
            pytest.param("bm3-4b", id="Input file"),
            pytest.param("bm3-4c", id="Input file"),
            pytest.param("bm3-4d", id="Input file"),
            pytest.param("bm3-4e", id="Input file"),
            pytest.param("bm3-4f", id="Input file"),
            pytest.param("bm3-5a", id="Input file"),
            pytest.param("bm3-5b", id="Input file"),
            pytest.param("bm3-5c", id="Input file"),
            pytest.param("bm3-5d", id="Input file"),
            pytest.param("bm3-6a", id="Input file"),
            pytest.param("bm3-6b", id="Input file"),
            pytest.param("bm3-7a", id="Input file"),
            pytest.param("bm3-7b", id="Input file"),
            pytest.param("bm3-7c", id="Input file"),
            pytest.param("bm3-7d", id="Input file"),
            pytest.param("bm3-7e", id="Input file"),
            pytest.param("bm3-7f", id="Input file"),
            pytest.param("bm3-7g", id="Input file"),
            pytest.param("bm3-7h", id="Input file"),
            pytest.param("bm3-7i", id="Input file"),
            pytest.param("bm3-7j", id="Input file"),
            pytest.param("bm3-7k", id="Input file"),
            pytest.param("bm3-7l", id="Input file"),
            pytest.param("bm3-7m", id="Input file"),
            pytest.param("bm3-7n", id="Input file"),
            pytest.param("bm3-7o", id="Input file"),
            pytest.param("bm3-7p", id="Input file"),
            pytest.param("bm3-7q", id="Input file"),
            pytest.param("bm3-7r", id="Input file"),
            pytest.param("bm3-8a", id="Input file"),
            pytest.param("bm3-8b", id="Input file"),
            pytest.param("bm3-8c", id="Input file"),
            pytest.param("bm3-8d", id="Input file"),
            pytest.param("bm3-8e", id="Input file"),
            pytest.param("bm3-8f", id="Input file"),
            pytest.param("bm3-9a", id="Input file"),
            pytest.param("bm3-9b", id="Input file"),
            pytest.param("bm3-9c", id="Input file"),
            pytest.param("bm3-9d", id="Input file"),
            pytest.param("bm3-9e", id="Input file"),
            pytest.param("bm3-9f", id="Input file"),
            pytest.param("bm4-10a", id="Input file"),
            pytest.param("bm4-10b", id="Input file"),
            pytest.param("bm4-10c", id="Input file"),
            pytest.param("bm4-10d", id="Input file"),
            pytest.param("bm4-10e", id="Input file"),
            pytest.param("bm4-10f", id="Input file"),
            pytest.param("bm4-10g", id="Input file"),
            pytest.param("bm4-10h", id="Input file"),
            pytest.param("bm4-10i", id="Input file"),
            pytest.param("bm4-11a", id="Input file"),
            pytest.param("bm4-11b", id="Input file"),
            pytest.param("bm4-11c", id="Input file"),
            pytest.param("bm4-11d", id="Input file"),
            pytest.param("bm4-12a", id="Input file"),
            pytest.param("bm4-12b", id="Input file"),
            pytest.param("bm4-1a", id="Input file"),
            pytest.param("bm4-1b", id="Input file"),
            pytest.param("bm4-2a", id="Input file"),
            pytest.param("bm4-2b", id="Input file"),
            pytest.param("bm4-2c", id="Input file"),
            pytest.param("bm4-2d", id="Input file"),
            pytest.param("bm4-3a", id="Input file"),
            pytest.param("bm4-3b", id="Input file"),
            pytest.param("bm4-3c", id="Input file"),
            pytest.param("bm4-3d", id="Input file"),
            pytest.param("bm4-3e", id="Input file"),
            pytest.param("bm4-3f", id="Input file"),
            pytest.param("bm4-3g", id="Input file"),
            pytest.param("bm4-3h", id="Input file"),
            pytest.param("bm4-3i", id="Input file"),
            pytest.param("bm4-3j", id="Input file"),
            pytest.param("bm4-3k", id="Input file"),
            pytest.param("bm4-3l", id="Input file"),
            pytest.param("bm4-4a", id="Input file"),
            pytest.param("bm4-4b", id="Input file"),
            pytest.param("bm4-4c", id="Input file"),
            pytest.param("bm4-4d", id="Input file"),
            pytest.param("bm4-4e", id="Input file"),
            pytest.param("bm4-4f", id="Input file"),
            pytest.param("bm4-4g", id="Input file"),
            pytest.param("bm4-4h", id="Input file"),
            pytest.param("bm4-4i", id="Input file"),
            pytest.param("bm4-4j", id="Input file"),
            pytest.param("bm4-4k", id="Input file"),
            pytest.param("bm4-4l", id="Input file"),
            pytest.param("bm4-4m", id="Input file"),
            pytest.param("bm4-4n", id="Input file"),
            pytest.param("bm4-4o", id="Input file"),
            pytest.param("bm4-4p", id="Input file"),
            pytest.param("bm4-4q", id="Input file"),
            pytest.param("bm4-4r", id="Input file"),
            pytest.param("bm4-4s", id="Input file"),
            pytest.param("bm4-4t", id="Input file"),
            pytest.param("bm4-4u", id="Input file"),
            pytest.param("bm4-4v", id="Input file"),
            pytest.param("bm4-5a", id="Input file"),
            pytest.param("bm4-5b", id="Input file"),
            pytest.param("bm4-5c", id="Input file"),
            pytest.param("bm4-5d", id="Input file"),
            pytest.param("bm4-5e", id="Input file"),
            pytest.param("bm4-5f", id="Input file"),
            pytest.param("bm4-5g", id="Input file"),
            pytest.param("bm4-6a", id="Input file"),
            pytest.param("bm4-6b", id="Input file"),
            pytest.param("bm4-6c", id="Input file"),
            pytest.param("bm4-6d", id="Input file"),
            pytest.param("bm4-6e", id="Input file"),
            pytest.param("bm4-6f", id="Input file"),
            pytest.param("bm4-7a", id="Input file"),
            pytest.param("bm4-7b", id="Input file"),
            pytest.param("bm4-7c", id="Input file"),
            pytest.param("bm4-7d", id="Input file"),
            pytest.param("bm4-7e", id="Input file"),
            pytest.param("bm4-7f", id="Input file"),
            pytest.param("bm4-8a", id="Input file"),
            pytest.param("bm4-8b", id="Input file"),
            pytest.param("bm4-8c", id="Input file"),
            pytest.param("bm4-8d", id="Input file"),
            pytest.param("bm4-9a", id="Input file"),
            pytest.param("bm4-9b", id="Input file"),
            pytest.param("bm4-9c", id="Input file"),
            pytest.param("bm4-9d", id="Input file"),
            pytest.param("bm4-9e", id="Input file"),
            pytest.param("bm4-9f", id="Input file"),
            pytest.param("bm5-1a", id="Input file"),
            pytest.param("bm5-1b", id="Input file"),
            pytest.param("bm5-1c", id="Input file"),
        ],
    )
    def test_parse_output_benchmarks(self, filename):
        # 1. Set up test data
        test_folder = Path(TestUtils.get_local_test_data_dir("dsettlement/benchmarks"))
        test_file = test_folder / (filename + ".sld")
        output_test_folder = Path(
            TestUtils.get_output_test_data_dir("dsettlement/benchmarks")
        )
        output_test_file = output_test_folder / (filename + ".json")
        ds = DSettlementModel()

        # 2. Verify initial expectations
        assert test_file.exists()

        # 3. Run test
        ds.parse(test_file)

        # Serialize to json for acceptance
        with open(output_test_file, "w") as io:
            io.write(ds.output.json(indent=4))
