name: ci-docs

on:
  push:
    branches:
    - master

jobs:
  Docs:
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.13"]
          os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up UV
        uses: astral-sh/setup-uv@v3

      - name: Cache UV virtualenv
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/uv
          key: uv--${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            uv--${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Install Dependencies
        run: uv sync --extra server
        
      - name: Build sphinx documentation
        run: |
          cd docs
          uv run python -m sphinx . build -b html -c .

      - name: Commit documentation changes
        run: |
          git clone https://github.com/Deltares/GEOLib.git --branch gh-pages --single-branch gh-pages
          rm -r -f gh-pages/dev
          mkdir gh-pages/dev
          cp -r docs/build/* gh-pages/dev
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update dev version documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
