name: ci-docs

on:
  push:
    branches:
    - master
    
permissions:
  contents: write

jobs:
  Docs:
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.13"]
          os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4

      - name: Cache Pixi
        uses: actions/cache@v3
        with:
          path: ~/.cache/pixi
          key: pixi-${{ runner.os }}-${{ hashFiles('**/pixi.lock') }}
          restore-keys: |
            pixi-${{ runner.os }}-

      - name: Install Dependencies
        run: pixi install -e docs
        
      - name: Build sphinx documentation
        run: pixi run --manifest-path -e docs . python -m sphinx docs docs/build -b html -c docs

      - name: Commit and push documentation changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/Deltares/GEOLib.git --branch gh-pages --single-branch gh-pages
          rm -r -f gh-pages/dev
          mkdir gh-pages/dev
          cp -r docs/build/* gh-pages/dev
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update dev version documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
          git push https://x-access-token:${GH_TOKEN}@github.com/Deltares/GEOLib.git gh-pages
